### ISSUE TITLE
On enter is always called on lazy element creation

### ISSUE THREAD

**Issue by minht11** [otonashixav/solid-flip#5]
If element is loaded lazily enter will be always called on it, even if element itself is initial child. 
```tsx
const Content = lazy(async () => {
  await wait(2000);

  return {
    default: () => <div class="target" />
  };
});
<TransitionGroup
        enter={animateEnter({
          keyframes: {
            opacity: [0, 1],
          },
        })}>
        {visibility() && <Content />}
</TransitionGroup>
```
[Reproduction](https://codesandbox.io/s/frosty-jepsen-xpi6f?file=/index.js:574-846)
Last working version was 0.5.7

**Comment by otonashixav** [comment]
This is due to 0.5.7's `animateEnter` not doing anything when it is first called unless `initial` was true. The behaviour was changed in 0.6.0 then 0.7.0. The current behaviour is for `TransitionGroup` to not do anything with the initial set of resolved children unless `initial` is a function (calls it) or true (calls `enter` if present), or `initial` is not false and `enter.initial` is present, in which case it calls `enter.initial`. This causes elements entering after the `TranstionGroup` is created to not be considered part of `initial` unlike before 0.6.0. 

To restore the previous behaviour, you can wrap `animateEnter` with another function that does nothing the first time, then calls the function returned by `animateEnter` subsequently:

```tsx
const enter = animateEnter();
let isInitial = true;
<TransitionGroup enter={(els) => isInitial ? isInitial = false : enter(els)}>
```

Another way of going about this (probably more "correct") would be to only create the `TransitionGroup` after the lazy component loads, but I don't see how to accomplish that with `Suspense` and `lazy`, while still keeping their benefits over using `createResource` used like so:

```tsx
const [Content] = createResource(async () => {
  await wait(2000);
  return () => <div class="target" />;
});

<Show when={!Content.loading}>
  <TransitionGroup
    enter={animateEnter({
      keyframes: {
        opacity: [0, 1]
      },
      options: { duration: 1000, easing: "linear" }
    })}
  >
    {visibility() && <Content />}
  </TransitionGroup>
</Show>
```

**Comment by otonashixav** [comment]
This is also possible, though depending on what `Content` is it may not be viable.
```tsx
const resolve = (el) => {
  while (typeof el === 'function') el = el();
  return el;
}
<Suspense>
  <Show when={resolve(Content)}>
    <TransitionGroup
      initial={() => console.log('initial')}
      enter={animateEnter({
        keyframes: {
          opacity: [0, 1]
        },
        options: { duration: 1000, easing: "linear" }
      })}
    >
      {visibility() && <Content />}
    </TransitionGroup>
  </Show>
</Suspense>
```

**Comment by minht11** [comment]
> This causes elements entering after the TranstionGroup is created to not be considered part of initial unlike before 0.6.0.

I missed that part inside the docs sorry, still it feels bit counter intuitive though, especially since lazy loading is pretty common pattern.

In any case the first solution will most likely work for me, as for the second one, all of my Routes should use the same animation and animate when route changes, so moving TransitionGroup inside the actual components is not possible.
```tsx
<TransitionGroup>
  <Suspense>
    <Routes />
  </Suspense>
</TransitionGroup>
```

**Comment by otonashixav** [comment]
> I missed that part inside the docs sorry, still it feels bit counter intuitive though, especially since lazy loading is pretty common pattern.

That makes sense actually. I don't see any reason not to delay `initial` until the children contain at least one element. I'll change the behaviour.

**Comment by otonashixav** [comment]
Fixed in 0.7.5.

**Comment by minht11** [comment]
Is it actually fixed, because I still see the same behavior [here](https://codesandbox.io/s/frosty-jepsen-xpi6f?file=/index.js) and locally?

Setting initial value as a callback doesn't even run for me anymore and enter animation is still appearing no matter what initial value is used.

**Comment by otonashixav** [comment]
My bad, published the wrong version to npm. Should be fine now (0.7.6).
